version: '3.8'
services:
  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_NODE_ID=1
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,PLAINTEXT_HOST://:29092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - CLUSTER_ID=MkU3OEVBNTcwNTJENDM2Qk
    healthcheck:
      test: ["CMD", "bash", "-lc", "kafka-topics --bootstrap-server localhost:9092 --list || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12

  producer:
    build: ./apps/producer
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS:-kafka:9092}
      - TOPIC=${TOPIC:-demo.events}
      - EVENTS_PER_SECOND=${EVENTS_PER_SECOND:-2}
    depends_on:
      kafka:
        condition: service_healthy
    restart: unless-stopped

  sink:
    build: ./apps/sink
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS:-kafka:9092}
      - TOPIC=${TOPIC:-demo.events}
      - FIREBOLT_CORE_URL=${FIREBOLT_CORE_URL:-http://host.docker.internal:3473}
      - FIREBOLT_DB=${FIREBOLT_DB:-demo_db}
      - FIREBOLT_TABLE=${FIREBOLT_TABLE:-demo_events}
    depends_on:
      kafka:
        condition: service_healthy
    restart: unless-stopped

  dashboard:
    build: ./apps/dashboard
    ports:
      - "8000:8000"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS:-kafka:9092}
      - TOPIC=${TOPIC:-demo.events}
      - FIREBOLT_CORE_URL=${FIREBOLT_CORE_URL:-http://host.docker.internal:3473}
      - FIREBOLT_DB=${FIREBOLT_DB:-demo_db}
    depends_on:
      kafka:
        condition: service_healthy
    restart: unless-stopped

networks:
  default:
    name: firebolt-demo-net
